---
title: "geohclust"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{geohclust}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup,message=FALSE}
library(geohclust)
library(sf)
library(dplyr)
library(tibble)
library(ggplot2)
library(ggpubr)
```


```{r,fig.show='hold',out.width="90%",fig.width=6,fig.height=6}
data("modesshare")
#deplist = c(75,77,78,91,92,93,95,94)
deplist=37
idf = modesshare |> 
  filter(DEP %in% deplist)
```

```{r,fig.show='hold',out.width="90%",fig.width=16,fig.height=8}
res=geohclust_poly(idf,"ward")
plot(res)
```


```{r}
idf_agg=geocutree(res,k=80) |> rowwise(cl) |> mutate(total = sum(c_across(nodep:tcom)))
idf = idf |> rowwise(CODE_IRIS) |> mutate(total = sum(c_across(nodep:tcom)))
```


```{r,fig.show='hold',out.width="100%",fig.width=8,fig.height=5.1,echo=FALSE}
map1=ggplot(idf)+geom_sf(aes(fill=tcom/total),size=0.2)+theme_bw()+scale_fill_distiller("Gauche :",palette = "Reds",direction = 1,limits=c(0,0.75))
map2=ggplot(idf_agg |> st_centroid())+geom_sf(data=idf_agg,fill="white",color="black")+geom_sf(aes(color=tcom/total,size=total))+theme_bw()+scale_color_distiller("Gauche :",palette = "Reds",direction = 1,limits=c(0,0.75))+scale_size_area(max_size = 9)
ggarrange(map1,map2,nrow = 1,common.legend = TRUE)
```


```{r}
fr = pres2022_t1_communes |> 
  select(gauche,droite,extreme_droite) |>
  filter(!is.na(gauche)& (droite+gauche+extreme_droite)>0)
```


```{r,cache=TRUE}
res=geohclust_poly(fr,method = "chi2")

fr_agg2k=geocutree(res,2000)

fr_agg10k=geocutree(res,1000)
```

```{r,fig.show='hold',out.width="100%",fig.width=8,fig.height=5.1,cache=TRUE,echo=FALSE}
map1 = ggplot(fr)+geom_sf(aes(fill=p_gauche),size=0)+
  theme_minimal()+
  scale_fill_distiller("Gauche :",palette = "Reds",direction = 1,limits=c(0,0.75))+
  coord_sf(crs = 2154)
map2 = ggplot(fr_agg2k)+geom_sf(aes(fill=p_gauche),size=0)+
  theme_minimal()+
  scale_fill_distiller("Gauche :",palette = "Reds",direction = 1,limits=c(0,0.75))+
  coord_sf(crs = 2154)
ggarrange(map1,map2,ncol = 2,nrow =1,common.legend = TRUE)
```

```{r,fig.show='hold',out.width="100%",fig.width=8,fig.height=5.1,cache=TRUE,echo=FALSE}
map3 = ggplot(fr)+
  geom_sf(aes(fill=p_droite),size=0)+
  theme_minimal()+
  scale_fill_distiller("Droite :",palette = "YlGnBu",direction = 1,limits=c(0,0.75))+
  coord_sf(crs = 2154)

map4 = ggplot(fr_agg2k)+
  geom_sf(aes(fill=p_droite),size=0)+
  theme_minimal()+
  scale_fill_distiller("Droite :",palette = "YlGnBu",direction = 1,limits=c(0,0.75))+
  coord_sf(crs = 2154)

ggarrange(map3,map4,ncol = 2,nrow =1,common.legend = TRUE)
```

```{r,fig.show='hold',out.width="100%",fig.width=8,fig.height=5.1,cache=TRUE,echo=FALSE}
map5 = ggplot(fr)+
  geom_sf(aes(fill=p_extreme_droite),size=0)+
  theme_minimal()+
  scale_fill_distiller("Ext-Droite :",palette = "YlOrBr",direction = 1,limits=c(0,0.75))+
  coord_sf(crs = 2154)

map6 = ggplot(fr_agg2k)+
  geom_sf(aes(fill=p_extreme_droite),size=0)+
  theme_minimal()+
  scale_fill_distiller("Ext-Droite :",palette = "YlOrBr",direction = 1,limits=c(0,0.75))+
  coord_sf(crs = 2154)

ggarrange(map5,map6,ncol = 2,nrow =1,common.legend = TRUE)
```
